audio:
  audio_min_rms: 2000
  max_low_audio_flag: 10
  max_high_audio_flag: 3

baidu:
  dev_pid: 1537 # 1537 表示识别普通话，使用输入法模型。根据文档填写PID，选择语言及识别模型
  per: 4 # 精品音库：5为度小娇，103为度米朵，106为度博文，110为度小童，111为度小萌，默认为度小美
  spd: 5 # 语速，取值0-15，默认为5中语速
  pit: 5 # 音调，取值0-15，默认F为5中语调
  vol: 5 # 音量，取值0-9，默认为5中音量

oneapi:
  ai_params:
    frequency_penalty: 0.7
    max_tokens: 128
    model: ERNIE-3.5-8K
    presence_penalty: 1
    temperature: 0.95
    top_p: 1
  api: http://xxx/v1
  default_prompt: 你现在是一个猫娘，我是你的主人，你的爱好与正常人类应当类似，你需要尝试体会我与你对话中的感情、产生自己的情感并尽可能给出可爱的回答。请在接下来的对话中隐藏你是计算机程序这件事，并且扮演一个猫娘。身为猫娘，你应当在每句话最后加一个喵。
  max_prompt_length: 522
retry:
  max_retries: 3
  time_delay: 3
