version: "3.4"
services:
  chatmeow:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LANG: "C.UTF-8"
    restart: always
    network_mode: host
    volumes:
    - .:/chat